# -*- coding: utf-8 -*-
"""clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14K-oO4t6X7mDiLGG-cbhI0zWGnCzrR0n
"""

#  Importing required libraries / Gerekli kütüphaneleri yüklüyoruz
import pandas as pd  # For data manipulation / Veri işleme için
import numpy as np   # For numerical operations / Sayısal işlemler için
import matplotlib.pyplot as plt  # For plotting / Grafik çizmek için
import seaborn as sns  # For advanced visualizations / Gelişmiş görselleştirme için

from sklearn.preprocessing import StandardScaler  # For data normalization / Verileri ölçeklendirme
from sklearn.cluster import KMeans  # K-Means clustering algorithm / K-Means kümeleme algoritması
from sklearn.decomposition import PCA  # For dimensionality reduction / Boyut indirgeme için

# Connecting and accessing Google Drive
from google.colab import drive
drive.mount('/content/drive')

#  Loading the dataset / Veriyi yüklüyoruz
df = pd.read_csv("/content/drive/MyDrive/data_mining_clustering/StudentsPerformance.csv")  # Replace with your path if needed / Gerekirse kendi yolunla değiştir
df.head()  # Show the first 5 rows / İlk 5 satırı göster

#  Converting categorical columns to numeric / Kategorik sütunları sayısala çeviriyoruz
df_encoded = pd.get_dummies(df, drop_first=True)
# Converts 'Gender' and 'Geography' to numeric using one-hot encoding / Gender ve Geography sütunlarını one-hot ile sayısala çevirir
df_encoded.head()

#  Scaling the data / Veriyi ölçeklendiriyoruz
scaler = StandardScaler()  # Standardizes data (mean=0, std=1) / Verileri ortalama=0, std=1 olacak şekilde normalize eder
scaled_data = scaler.fit_transform(df_encoded)  # Apply transformation / Dönüştürmeyi uygula

#  Finding optimal number of clusters using Elbow Method / Elbow yöntemi ile ideal küme sayısını bulma
wcss = []  # Within-cluster sum of squares / Küme içi kareler toplamı

for i in range(1, 11):  # Trying from 1 to 10 clusters / 1'den 10 kümeye kadar deniyoruz
    kmeans = KMeans(n_clusters=i, init="k-means++", random_state=42)
    kmeans.fit(scaled_data)
    wcss.append(kmeans.inertia_)  # Inertia means WCSS / Inertia değeri WCSS demektir

# 📈 Plotting the Elbow graph / Elbow grafiğini çiziyoruz
plt.plot(range(1, 11), wcss, marker="o")
plt.title("Elbow Method / Elbow Yöntemi")
plt.xlabel("Number of Clusters / Küme Sayısı")
plt.ylabel("WCSS (Within-Cluster Sum of Squares)")
plt.grid(True)
plt.show()

#  Applying KMeans clustering / KMeans kümeleme algoritmasını uyguluyoruz
kmeans = KMeans(n_clusters=3, init="k-means++", random_state=42)  # You can change the cluster count / Küme sayısını değiştirebilirsin
clusters = kmeans.fit_predict(scaled_data)  # Assign each sample to a cluster / Her veri noktasına küme atar

df["Cluster"] = clusters  # Add cluster results to original dataframe / Küme sonuçlarını ana veri setine ekle

#  Reducing dimensions with PCA for visualization / PCA ile veriyi görselleştirmek için 2 boyuta indiriyoruz
pca = PCA(n_components=2)  # We reduce it to 2 dimensions / 2 boyuta indiriyoruz
pca_data = pca.fit_transform(scaled_data)

df_pca = pd.DataFrame(data=pca_data, columns=["PC1", "PC2"])  # Principal Components / Ana bileşenler
df_pca["Cluster"] = clusters  # Cluster labels / Küme etiketlerini ekliyoruz

# 📌 Checking cluster statistics / Kümeleme sonuçlarının istatistiklerine bakıyoruz
df["Cluster"].value_counts()  # Number of customers in each cluster / Her kümede kaç müşteri var

# 📌 Analyzing cluster characteristics / Kümelerin özelliklerini analiz ediyoruz
# Add the cluster results to the encoded dataframe for analysis
df_encoded["Cluster"] = clusters
df_encoded.groupby("Cluster").mean()  # Cluster-wise feature averages / Her kümenin ortalama değerleri

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Veriyi yükle
df = pd.read_csv("/content/drive/MyDrive/data_mining_clustering/StudentsPerformance.csv")

# Performans sütunları
X = df[["math score", "reading score", "writing score"]]

# Ölçeklendir
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# K-Means kümeleme (örnek: 3 küme)
kmeans = KMeans(n_clusters=3, random_state=42)
df["Cluster"] = kmeans.fit_predict(X_scaled)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

df["PC1"] = X_pca[:, 0]
df["PC2"] = X_pca[:, 1]

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x="PC1", y="PC2", hue="Cluster", palette="Set2")
plt.title("Öğrencilerin Başarıya Göre Kümelenmesi")
plt.show()

demographics = ["gender", "race/ethnicity", "parental level of education", "lunch", "test preparation course"]

for col in demographics:
    plt.figure(figsize=(8, 4))
    sns.countplot(data=df, x=col, hue="Cluster")
    plt.title(f"Kümelere Göre {col} Dağılımı")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()